"""Backs the dashboard's OAuth consent page (app/(app)/oauth/authorize)
-- the human-facing half of the MCP server's login flow. The actual OAuth
protocol endpoints (discovery, dynamic client registration, /authorize,
/token, /revoke) are generated by the mcp package itself from
TracynOAuthProvider (see services/mcp_oauth_provider.py and
configure_oauth in main.py); this router only covers the two things that
provider can't do on its own, since they need a real logged-in user:
showing what's being requested, and recording that user's decision."""

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

from app.db import get_db, run_db
from app.security import CurrentUser, get_current_user
from app.services.mcp_oauth_provider import get_oauth_provider, mint_api_key_for_workspace

router = APIRouter(prefix="/v1/oauth", tags=["oauth"])

_EXPIRED_DETAIL = "This connection request has expired or was already used. Try connecting again from the app you're adding Tracyn to."


class ConsentDecisionIn(BaseModel):
    request_id: str
    workspace_id: str


class DenyIn(BaseModel):
    request_id: str


@router.get("/consent")
async def get_consent_info(request_id: str, user: CurrentUser = Depends(get_current_user)) -> dict:
    pending = get_oauth_provider().get_pending(request_id)
    if pending is None:
        raise HTTPException(status_code=404, detail=_EXPIRED_DETAIL)

    db = get_db()
    memberships = (
        await run_db(lambda: db.table("workspace_members").select("workspace_id").eq("user_id", user.id).execute())
    ).data
    workspace_ids = [m["workspace_id"] for m in memberships]
    workspaces = []
    if workspace_ids:
        workspaces = (
            await run_db(lambda: db.table("workspaces").select("id, name").in_("id", workspace_ids).execute())
        ).data

    client = pending.client
    return {
        "client_name": client.client_name or client.client_uri or "An MCP client",
        "client_uri": str(client.client_uri) if client.client_uri else None,
        "scopes": pending.params.scopes or ["mcp"],
        "workspaces": workspaces,
    }


@router.post("/consent")
async def submit_consent(body: ConsentDecisionIn, user: CurrentUser = Depends(get_current_user)) -> dict:
    provider = get_oauth_provider()
    pending = provider.get_pending(body.request_id)
    if pending is None:
        raise HTTPException(status_code=404, detail=_EXPIRED_DETAIL)

    db = get_db()
    membership = (
        await run_db(
            lambda: db.table("workspace_members")
            .select("user_id")
            .eq("workspace_id", body.workspace_id)
            .eq("user_id", user.id)
            .limit(1)
            .execute()
        )
    ).data
    if not membership:
        raise HTTPException(status_code=403, detail="Not a member of that workspace")

    client_label = pending.client.client_name or pending.client.client_uri or "Unknown app"
    api_key = await mint_api_key_for_workspace(body.workspace_id, name=f"MCP: {client_label}", created_by=user.id)

    redirect_url = provider.complete_authorization(body.request_id, api_key=api_key, subject=body.workspace_id)
    if redirect_url is None:
        # Vanishingly unlikely (would need the request to expire in the
        # instant between the check above and here), but handle it rather
        # than assume complete_authorization can't fail after get_pending
        # just succeeded.
        raise HTTPException(status_code=404, detail=_EXPIRED_DETAIL)
    return {"redirect_url": redirect_url}


@router.post("/deny")
async def deny_consent(body: DenyIn, user: CurrentUser = Depends(get_current_user)) -> dict:
    redirect_url = get_oauth_provider().deny_authorization(body.request_id)
    if redirect_url is None:
        raise HTTPException(status_code=404, detail=_EXPIRED_DETAIL)
    return {"redirect_url": redirect_url}
