"""Integration tests for the OAuth consent router (routers/oauth.py) --
the human-facing half of the MCP server's login flow, exercised through
the real FastAPI app. The OAuth *protocol* endpoints themselves
(discovery, registration, /authorize, /token) are generated by the mcp
package from TracynOAuthProvider and covered separately in
test_mcp_oauth_provider.py; this file covers what only a real logged-in
dashboard user can do: seeing what's being requested and deciding it,
including that a real, persisted, workspace-scoped API key gets minted
on approval, and that no dashboard user can approve a workspace they
don't belong to."""

import pytest
from fastapi.testclient import TestClient
from mcp.server.auth.provider import AuthorizationParams
from mcp.shared.auth import OAuthClientInformationFull

from app.main import app
from app.security import CurrentUser, get_current_user
from app.services.mcp_oauth_provider import TracynOAuthProvider

USER_ID = "user-1"
WORKSPACE_ID = "ws-1"
OTHER_WORKSPACE_ID = "ws-other"


class _FakeResult:
    def __init__(self, data):
        self.data = data


class _FakeQuery:
    def __init__(self, table, op, payload=None):
        self.table = table
        self.op = op
        self.payload = payload
        self.filters = {}
        self.in_filter = None

    def eq(self, field, value):
        self.filters[field] = value
        return self

    def in_(self, field, values):
        self.in_filter = (field, set(values))
        return self

    def limit(self, _n):
        return self

    def execute(self):
        rows = self.table.rows

        if self.op == "insert":
            row = {"id": f"row-{len(rows) + 1}", **self.payload}
            rows[row["id"]] = row
            return _FakeResult([row])

        matches = [r for r in rows.values() if all(r.get(k) == v for k, v in self.filters.items())]
        if self.in_filter:
            field, values = self.in_filter
            matches = [r for r in matches if r.get(field) in values]
        return _FakeResult(matches)


class _FakeTable:
    def __init__(self, rows):
        self.rows = rows

    def select(self, *_a, **_kw):
        return _FakeQuery(self, "select")

    def insert(self, payload):
        return _FakeQuery(self, "insert", payload)


class _FakeDb:
    def __init__(self):
        self._tables = {
            "workspace_members": {
                "m1": {"workspace_id": WORKSPACE_ID, "user_id": USER_ID},
            },
            "workspaces": {
                WORKSPACE_ID: {"id": WORKSPACE_ID, "name": "Acme Inc"},
                OTHER_WORKSPACE_ID: {"id": OTHER_WORKSPACE_ID, "name": "Someone Else's Workspace"},
            },
            "api_keys": {},
        }

    def table(self, name):
        return _FakeTable(self._tables.setdefault(name, {}))


@pytest.fixture
def fake_db(monkeypatch):
    db = _FakeDb()
    monkeypatch.setattr("app.routers.oauth.get_db", lambda: db)
    monkeypatch.setattr("app.services.mcp_oauth_provider.get_db", lambda: db)
    return db


@pytest.fixture
def provider(monkeypatch):
    # A fresh instance per test, not the real process-wide singleton
    # (get_oauth_provider is @lru_cache'd) -- avoids one test's pending
    # requests leaking into another's.
    p = TracynOAuthProvider(dashboard_base_url="https://app.example.com")
    monkeypatch.setattr("app.routers.oauth.get_oauth_provider", lambda: p)
    return p


@pytest.fixture
def client(fake_db, provider):
    app.dependency_overrides[get_current_user] = lambda: CurrentUser(id=USER_ID, email="owner@example.com")
    with TestClient(app) as c:
        yield c
    app.dependency_overrides.clear()


async def _seed_pending_request(provider: TracynOAuthProvider, *, redirect_uri="https://claude.ai/callback") -> str:
    client_info = OAuthClientInformationFull(client_id="client-1", client_name="Claude", redirect_uris=[redirect_uri])
    params = AuthorizationParams(
        state="xyz", scopes=["mcp"], code_challenge="chal", redirect_uri=redirect_uri, redirect_uri_provided_explicitly=True
    )
    url = await provider.authorize(client_info, params)
    return url.rsplit("=", 1)[1]


def test_get_consent_requires_login(fake_db, provider):
    with TestClient(app) as c:
        resp = c.get("/v1/oauth/consent", params={"request_id": "whatever"})
    assert resp.status_code == 401


def test_get_consent_returns_404_for_an_unknown_request(client):
    resp = client.get("/v1/oauth/consent", params={"request_id": "does-not-exist"})
    assert resp.status_code == 404


@pytest.mark.anyio
async def test_get_consent_shows_the_clients_name_and_the_users_workspaces(client, provider):
    request_id = await _seed_pending_request(provider)

    resp = client.get("/v1/oauth/consent", params={"request_id": request_id})

    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["client_name"] == "Claude"
    assert body["workspaces"] == [{"id": WORKSPACE_ID, "name": "Acme Inc"}]
    assert OTHER_WORKSPACE_ID not in [w["id"] for w in body["workspaces"]]


@pytest.mark.anyio
async def test_approving_consent_mints_a_real_api_key_and_redirects_with_a_code(client, provider, fake_db):
    request_id = await _seed_pending_request(provider)

    resp = client.post("/v1/oauth/consent", json={"request_id": request_id, "workspace_id": WORKSPACE_ID})

    assert resp.status_code == 200, resp.text
    redirect_url = resp.json()["redirect_url"]
    assert redirect_url.startswith("https://claude.ai/callback?")
    assert "code=" in redirect_url
    assert "state=xyz" in redirect_url

    # A real, persisted, workspace-scoped API key -- same table, same
    # shape, as one created by hand in Settings.
    created = list(fake_db._tables["api_keys"].values())
    assert len(created) == 1
    assert created[0]["workspace_id"] == WORKSPACE_ID
    assert created[0]["created_by"] == USER_ID
    assert "Claude" in created[0]["name"]


@pytest.mark.anyio
async def test_cannot_approve_consent_for_a_workspace_you_are_not_a_member_of(client, provider, fake_db):
    request_id = await _seed_pending_request(provider)

    resp = client.post("/v1/oauth/consent", json={"request_id": request_id, "workspace_id": OTHER_WORKSPACE_ID})

    assert resp.status_code == 403
    assert fake_db._tables["api_keys"] == {}


@pytest.mark.anyio
async def test_approving_consent_twice_fails_the_second_time(client, provider):
    request_id = await _seed_pending_request(provider)
    client.post("/v1/oauth/consent", json={"request_id": request_id, "workspace_id": WORKSPACE_ID})

    resp = client.post("/v1/oauth/consent", json={"request_id": request_id, "workspace_id": WORKSPACE_ID})

    assert resp.status_code == 404


@pytest.mark.anyio
async def test_denying_consent_redirects_with_access_denied_and_mints_nothing(client, provider, fake_db):
    request_id = await _seed_pending_request(provider)

    resp = client.post("/v1/oauth/deny", json={"request_id": request_id})

    assert resp.status_code == 200, resp.text
    assert "error=access_denied" in resp.json()["redirect_url"]
    assert fake_db._tables["api_keys"] == {}


def test_deny_returns_404_for_an_unknown_request(client):
    resp = client.post("/v1/oauth/deny", json={"request_id": "does-not-exist"})
    assert resp.status_code == 404
